### ISSUE TITLE
JOCLSimpleImage Runtime Error

### ISSUE THREAD

**Issue by tpavelka** [gpu/JOCLSamples#1]
Exception in thread "AWT-EventQueue-0" org.jocl.CLException: CL_INVALID_QUEUE_PROPERTIES
	at org.jocl.CL.checkResult(CL.java:825)
	at org.jocl.CL.clCreateCommandQueueWithProperties(CL.java:5383)
	at JOCLSimpleImage.initCL(JOCLSimpleImage.java:290)
	at JOCLSimpleImage.<init>(JOCLSimpleImage.java:190)
	at JOCLSimpleImage$1.run(JOCLSimpleImage.java:38)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by tpavelka** [comment]
OpenCL 2.1
![Ellesmere](https://user-images.githubusercontent.com/22208769/91348722-cfcc8d80-e7a9-11ea-81dd-ed3691a2137a.png)

**Comment by tpavelka** [comment]
This error was fixed by deleting the following lines in JOCLSimpleImage.java::~Line230:

        properties.addProperty(CL_QUEUE_PROFILING_ENABLE, 1);
        properties.addProperty(CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE, 1);

**Comment by gpu** [comment]
(Again: Sorry for the delay...)

According to the device info that you showed, the `CL_QUEUE_PROFILING_ENABLE` property should be supported. It does not support the `CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE`, so it should be sufficient to remove that. (I'll have to review why I added this in the first place, but it should not be critical here).
